#ifndef ONE_CHALLENGES_H
#define ONE_CHALLENGES_H

#include "types.h"

typedef u64 oneflags_t;

enum OneChallengeStatus {
    CHALLENGE_STATUS_NOT_PLAYING,
    CHALLENGE_STATUS_PLAYING,
    CHALLENGE_STATUS_CAN_WIN,
    CHALLENGE_STATUS_WIN,
    CHALLENGE_STATUS_LOSE
};

enum OneChallengeEntries {
    CHALLENGE_NAME_SMOOCH,
    CHALLENGE_NAME_JUMP,
    CHALLENGE_NAME_COIN,
    CHALLENGE_NAME_GROUND,
    CHALLENGE_NAME_A_PRESS,
    CHALLENGE_NAME_B_PRESS,
    CHALLENGE_NAME_WALLKICK,
    CHALLENGE_NAME_TRIPLE_JUMP,
    CHALLENGE_NAME_COLLECT_LIFE,
    CHALLENGE_NAME_SLEEPING_PIRANHA,
    CHALLENGE_NAME_KILL_GOOMBA,
    CHALLENGE_NAME_KILL_KOOPA,
    CHALLENGE_NAME_KILL_PENGUIN,
    CHALLENGE_NAME_KILL_BOMB,
    CHALLENGE_NAME_KILL_ALL_BOMBS,
    CHALLENGE_NAME_KILL_GOOMBA_WITH_BOMB,
    CHALLENGE_NAME_KILL_WHOMP_KING,
    CHALLENGE_NAME_KILL_MONEYBAG,
    CHALLENGE_NAME_INTERACTED_KOOPA,

    CHALLENGE_NAME_TIMER, // Must be last
    CHALLENGE_NAME_TOTAL,
};

enum OneChallengeChallenges {
    CHAL_ID_DUMMY_CHALLENGE,
    CHAL_ID_LEARNING_THE_ROPES,
    CHAL_ID_COIN_PARANOIA,
    CHAL_ID_GOOMBOUNCING,
    CHAL_ID_SHREDDING_SAFELY,
    CHAL_ID_BOBOMB_SACRIFICE,
    CHAL_ID_THE_LONE_SURVIVOR,
    CHAL_ID_OFF_THE_WALL_TO_GLORY,
    CHAL_ID_BOBOMB_BOWLING,
    CHAL_ID_DIMENSION_OF_THE_LIVING_KOOPA,
    CHAL_ID_TRICKY_TRIPLE,
    CHAL_ID_PIECE_OF_KOEK,
    CHAL_ID_THE_GREEN_DEMONS,
    CHAL_ID_PIRANHA_PLANT_SIESTA,
    CHAL_ID_PIRANHA_CHAINING,
    CHAL_ID_BOBOMB_BATTLE_ROYALE,
    CHAL_ID_A_SIMPLE_COIN,
    CHAL_ID_PLATFORMING,
    CHAL_ID_CAST_IT_INTO_THE_FIRE,
    CHAL_ID_THE_GREEN_DEMONS_POSSE,
    CHAL_ID_RESCUE_PEACH,
    CHAL_ID_TODO_21,
    CHAL_ID_TODO_22,
    CHAL_ID_TODO_23,
    CHAL_ID_TODO_24,
    CHAL_ID_TODO_25,
    CHAL_ID_TODO_26,
    CHAL_ID_TODO_27,
    CHAL_ID_TODO_28,
    CHAL_ID_TODO_29,
    CHAL_ID_TODO_30,
    CHAL_ID_TODO_31,
    CHAL_ID_TODO_32,
    CHAL_ID_TODO_33,
    CHAL_ID_TODO_34,
    CHAL_ID_TODO_35,
    CHAL_ID_TODO_36,
    CHAL_ID_TODO_37,
    CHAL_ID_TODO_38,
    CHAL_ID_TODO_39,
    CHAL_ID_TODO_40,
    CHAL_ID_TODO_41,
    CHAL_ID_TODO_42,
    CHAL_ID_TODO_43,
    CHAL_ID_TODO_44,
    CHAL_ID_TODO_45,
    CHAL_ID_TODO_46,
    CHAL_ID_TODO_47,
    CHAL_ID_TODO_48,
    CHAL_ID_TODO_49,
    CHAL_ID_TODO_50,
    CHAL_ID_TODO_51,
    CHAL_ID_TODO_52,
    CHAL_ID_TODO_53,
    CHAL_ID_TODO_54,
    CHAL_ID_TODO_55,
    CHAL_ID_TODO_56,
    CHAL_ID_TODO_57,
    CHAL_ID_TODO_58,
    CHAL_ID_TODO_59,
    CHAL_ID_TODO_60,
    CHAL_ID_TODO_61,
    CHAL_ID_TODO_62,
    CHAL_ID_TODO_63,
};

STATIC_ASSERT(CHALLENGE_NAME_TOTAL <= sizeof(oneflags_t) * 8, "Too many challenges!");

enum OneChallengeFlags {
    CHALLENGE_FLAG_NONE                  = 0,

    CHALLENGE_FLAG_SMOOCH                = (1ULL << CHALLENGE_NAME_SMOOCH),
    CHALLENGE_FLAG_JUMP                  = (1ULL << CHALLENGE_NAME_JUMP),
    CHALLENGE_FLAG_COIN                  = (1ULL << CHALLENGE_NAME_COIN),
    CHALLENGE_FLAG_GROUND                = (1ULL << CHALLENGE_NAME_GROUND),
    CHALLENGE_FLAG_A_PRESS               = (1ULL << CHALLENGE_NAME_A_PRESS),
    CHALLENGE_FLAG_B_PRESS               = (1ULL << CHALLENGE_NAME_B_PRESS),
    CHALLENGE_FLAG_WALLKICK              = (1ULL << CHALLENGE_NAME_WALLKICK),
    CHALLENGE_FLAG_TRIPLE_JUMP           = (1ULL << CHALLENGE_NAME_TRIPLE_JUMP),
    CHALLENGE_FLAG_COLLECT_LIFE          = (1ULL << CHALLENGE_NAME_COLLECT_LIFE),
    CHALLENGE_FLAG_SLEEPING_PIRANHA      = (1ULL << CHALLENGE_NAME_SLEEPING_PIRANHA),
    CHALLENGE_FLAG_KILL_GOOMBA           = (1ULL << CHALLENGE_NAME_KILL_GOOMBA),
    CHALLENGE_FLAG_KILL_KOOPA            = (1ULL << CHALLENGE_NAME_KILL_KOOPA),
    CHALLENGE_FLAG_KILL_PENGUIN          = (1ULL << CHALLENGE_NAME_KILL_PENGUIN),
    CHALLENGE_FLAG_KILL_BOMB             = (1ULL << CHALLENGE_NAME_KILL_BOMB),
    CHALLENGE_FLAG_KILL_ALL_BOMBS        = (1ULL << CHALLENGE_NAME_KILL_ALL_BOMBS),
    CHALLENGE_FLAG_KILL_GOOMBA_WITH_BOMB = (1ULL << CHALLENGE_NAME_KILL_GOOMBA_WITH_BOMB),
    CHALLENGE_FLAG_KILL_WHOMP_KING       = (1ULL << CHALLENGE_NAME_KILL_WHOMP_KING),
    CHALLENGE_FLAG_KILL_MONEYBAG         = (1ULL << CHALLENGE_NAME_KILL_MONEYBAG),
    CHALLENGE_FLAG_INTERACTED_KOOPA      = (1ULL << CHALLENGE_NAME_INTERACTED_KOOPA),

    CHALLENGE_FLAG_TIMER                 = (1ULL << CHALLENGE_NAME_TIMER), // Must be last
};

struct OneChallengeLevel {
    u8 warpLevelNum;
    u8 warpAreaIdx;
    u8 warpNodeId;
    char *challengeName;
    oneflags_t requiredFlags; // "At least one of"
    oneflags_t enforcedFlags; // "No more than one of"
};

extern struct OneChallengeLevel gChallengeLevelData[sizeof(oneflags_t)*8];
extern u8 gChallengeLevel;
extern u16 gBombsSpawned;
extern u32 gChallengeStatus;
extern s32 gChallengeTimer;
extern s32 gMoneybagSwap;
extern s32 gMoneybagCount;
extern u8 gSetChallengeMusic;
extern u8 gWaitingToStart;

u8 is_challenge_active(void);
oneflags_t get_challenge_obtained_flags(void);
oneflags_t get_challenge_enforced_flags(void);
oneflags_t get_challenge_required_flags(void);
oneflags_t get_challenge_failure_flags(void);

void reset_challenge(void);
void start_next_challenge_level(void);
void start_challenge(void);
void add_challenge_flags(oneflags_t flags);
void add_challenge_kill_flags(oneflags_t flags);

void challenge_update(void);

#endif // ONE_CHALLENGES_H
