extern const GeoLayout moving_platform_geo_challenge_10_larger_geo[];
extern Vtx moving_platform_geo_challenge_10_larger_moving_platform_geo_challenge_10_larger_mesh_layer_1_vtx_cull[8];
extern Vtx moving_platform_geo_challenge_10_larger_moving_platform_geo_challenge_10_larger_mesh_layer_1_vtx_0[24];
extern Gfx moving_platform_geo_challenge_10_larger_moving_platform_geo_challenge_10_larger_mesh_layer_1_tri_0[];
extern Gfx mat_moving_platform_geo_challenge_10_larger_cozies_noise_thing_2_layer1[];
extern Gfx mat_revert_moving_platform_geo_challenge_10_larger_cozies_noise_thing_2_layer1[];
extern Gfx moving_platform_geo_challenge_10_larger_moving_platform_geo_challenge_10_larger_mesh_layer_1[];
extern Gfx moving_platform_geo_challenge_10_larger_material_revert_render_settings[];
