extern const GeoLayout outline_star_geo[];
extern u8 outline_star_cloud_deeper_i4_i8[];
extern Vtx outline_star_anocollect_mask_mesh_layer_7_vtx_cull[8];
extern Vtx outline_star_anocollect_mask_mesh_layer_7_vtx_0[14];
extern Gfx outline_star_anocollect_mask_mesh_layer_7_tri_0[];
extern Vtx outline_star_no_collect_mesh_layer_7_vtx_cull[8];
extern Vtx outline_star_no_collect_mesh_layer_7_vtx_0[13];
extern Gfx outline_star_no_collect_mesh_layer_7_tri_0[];
extern Gfx mat_outline_star_write_z_layer7[];
extern Gfx mat_revert_outline_star_write_z_layer7[];
extern Gfx mat_outline_star_f3dlite_material_004_layer7[];
extern Gfx mat_revert_outline_star_f3dlite_material_004_layer7[];
extern Gfx outline_star_anocollect_mask_mesh_layer_7[];
extern Gfx outline_star_no_collect_mesh_layer_7[];
extern Gfx outline_star_material_revert_render_settings[];
