extern const GeoLayout moving_platform_geo_challenge_10_wf_geo[];
extern Vtx moving_platform_geo_challenge_10_wf_moving_platform_geo_challenge_10_wf_mesh_layer_1_vtx_cull[8];
extern Vtx moving_platform_geo_challenge_10_wf_moving_platform_geo_challenge_10_wf_mesh_layer_1_vtx_0[24];
extern Gfx moving_platform_geo_challenge_10_wf_moving_platform_geo_challenge_10_wf_mesh_layer_1_tri_0[];
extern Gfx mat_moving_platform_geo_challenge_10_wf_cozies_noise_thing_2_layer1[];
extern Gfx mat_revert_moving_platform_geo_challenge_10_wf_cozies_noise_thing_2_layer1[];
extern Gfx moving_platform_geo_challenge_10_wf_moving_platform_geo_challenge_10_wf_mesh_layer_1[];
extern Gfx moving_platform_geo_challenge_10_wf_material_revert_render_settings[];
