extern const GeoLayout rr_area_1_geo[];
extern const GeoLayout rr_dl_Room1_geo[];
extern const GeoLayout rr_dl_Room2_geo[];
extern const GeoLayout rr_dl_Room3_geo[];
extern const GeoLayout rr_dl_Room4_geo[];
extern const GeoLayout rr_area_1[];
extern const Collision rr_area_1_collision[];
extern const u8 rr_area_1_collision_rooms[];
extern const MacroObject rr_area_1_macro_objs[];
extern const Trajectory rr_area_1_spline_NurbsCurve[];
extern const Trajectory rr_area_1_spline_NurbsCurve_001[];
extern const Trajectory rr_area_1_spline_NurbsCurve_002[];
extern const Trajectory rr_area_1_spline_NurbsCurve_003[];
extern u8 rr_dl_cutefirst_ci4[];
extern u8 rr_dl_cutefirst_ci4_pal_rgba16[];
extern Vtx rr_dl_Cube_001_mesh_layer_0_vtx_cull[8];
extern Vtx rr_dl_Cube_001_mesh_layer_0_vtx_0[117];
extern Gfx rr_dl_Cube_001_mesh_layer_0_tri_0[];
extern Vtx rr_dl_Room1Platform_mesh_layer_0_vtx_cull[8];
extern Vtx rr_dl_Room1Platform_mesh_layer_0_vtx_0[24];
extern Gfx rr_dl_Room1Platform_mesh_layer_0_tri_0[];
extern Vtx rr_dl_Room1Platform_001_mesh_layer_0_vtx_cull[8];
extern Vtx rr_dl_Room1Platform_001_mesh_layer_0_vtx_0[192];
extern Gfx rr_dl_Room1Platform_001_mesh_layer_0_tri_0[];
extern Vtx rr_dl_Room2Platform_mesh_layer_0_vtx_cull[8];
extern Vtx rr_dl_Room2Platform_mesh_layer_0_vtx_0[110];
extern Gfx rr_dl_Room2Platform_mesh_layer_0_tri_0[];
extern Vtx rr_dl_Room3PlatformTransitionFrom1To4_mesh_layer_0_vtx_cull[8];
extern Vtx rr_dl_Room3PlatformTransitionFrom1To4_mesh_layer_0_vtx_0[102];
extern Gfx rr_dl_Room3PlatformTransitionFrom1To4_mesh_layer_0_tri_0[];
extern Vtx rr_dl_Suzanne_mesh_layer_0_vtx_cull[8];
extern Vtx rr_dl_Suzanne_mesh_layer_0_vtx_0[890];
extern Gfx rr_dl_Suzanne_mesh_layer_0_tri_0[];
extern Vtx rr_dl_Suzanne_001_mesh_layer_0_vtx_cull[8];
extern Vtx rr_dl_Suzanne_001_mesh_layer_0_vtx_0[120];
extern Gfx rr_dl_Suzanne_001_mesh_layer_0_tri_0[];
extern Vtx rr_dl_Suzanne_002_mesh_layer_0_vtx_cull[8];
extern Vtx rr_dl_Suzanne_002_mesh_layer_0_vtx_0[120];
extern Gfx rr_dl_Suzanne_002_mesh_layer_0_tri_0[];
extern Vtx rr_dl_Torus_mesh_layer_0_vtx_cull[8];
extern Vtx rr_dl_Torus_mesh_layer_0_vtx_0[72];
extern Gfx rr_dl_Torus_mesh_layer_0_tri_0[];
extern Vtx rr_dl_Room4Platform_mesh_layer_0_vtx_cull[8];
extern Vtx rr_dl_Room4Platform_mesh_layer_0_vtx_0[104];
extern Gfx rr_dl_Room4Platform_mesh_layer_0_tri_0[];
extern Gfx mat_rr_dl_death_layer0[];
extern Gfx mat_revert_rr_dl_death_layer0[];
extern Gfx mat_rr_dl_sm64_material_001_layer0[];
extern Gfx mat_revert_rr_dl_sm64_material_001_layer0[];
extern Gfx rr_dl_Cube_001_mesh_layer_0[];
extern Gfx rr_dl_Room1Platform_mesh_layer_0[];
extern Gfx rr_dl_Room1Platform_001_mesh_layer_0[];
extern Gfx rr_dl_Room2Platform_mesh_layer_0[];
extern Gfx rr_dl_Room3PlatformTransitionFrom1To4_mesh_layer_0[];
extern Gfx rr_dl_Suzanne_mesh_layer_0[];
extern Gfx rr_dl_Suzanne_001_mesh_layer_0[];
extern Gfx rr_dl_Suzanne_002_mesh_layer_0[];
extern Gfx rr_dl_Torus_mesh_layer_0[];
extern Gfx rr_dl_Room4Platform_mesh_layer_0[];
extern Gfx rr_dl_material_revert_render_settings[];
