extern const GeoLayout bob_area_1_geo[];
extern const GeoLayout bob_area_1[];
extern const Collision bob_area_1_collision[];
extern const MacroObject bob_area_1_macro_objs[];
extern const GeoLayout bob_area_2_geo[];
extern const GeoLayout bob_area_2[];
extern const Collision bob_area_2_collision[];
extern const MacroObject bob_area_2_macro_objs[];
extern const GeoLayout bob_area_3_geo[];
extern const GeoLayout bob_area_3[];
extern const Collision bob_area_3_collision[];
extern const MacroObject bob_area_3_macro_objs[];
extern const GeoLayout bob_area_4_geo[];
extern const GeoLayout bob_area_4[];
extern const Collision bob_area_4_collision[];
extern const MacroObject bob_area_4_macro_objs[];
extern const GeoLayout bob_area_5_geo[];
extern const GeoLayout bob_area_5[];
extern const Collision bob_area_5_collision[];
extern const MacroObject bob_area_5_macro_objs[];
extern const GeoLayout bob_area_6_geo[];
extern const GeoLayout bob_area_6[];
extern const Collision bob_area_6_collision[];
extern const MacroObject bob_area_6_macro_objs[];
extern const Trajectory bob_area_6_spline_ASplineChallenge07[];
extern const Trajectory bob_area_6_spline_ASplineChallenge0A_001[];
extern const Trajectory bob_area_6_spline_ASplineChallenge0A_002[];
extern const Trajectory bob_area_6_spline_ASplineChallenge0A_003[];
extern const Trajectory bob_area_6_spline_ASplineChallenge0B[];
extern const Trajectory bob_area_6_spline_ASplineChallenge0A[];
extern const GeoLayout bob_area_7_geo[];
extern const GeoLayout bob_area_7[];
extern const Collision bob_area_7_collision[];
extern const MacroObject bob_area_7_macro_objs[];
extern const GeoLayout bob_area_8_geo[];
extern const GeoLayout bob_area_8[];
extern const Collision bob_area_8_collision[];
extern const MacroObject bob_area_8_macro_objs[];
extern const GeoLayout bob_area_9_geo[];
extern const GeoLayout bob_area_9[];
extern const Collision bob_area_9_collision[];
extern const MacroObject bob_area_9_macro_objs[];
extern u8 bob_dl_Z2_00KEIKOKUTex_02C050_rgba16_rgba16[];
extern u8 bob_dl_Grass_rgba16[];
extern u8 bob_dl_LightWall_64x64_ci4_ci4[];
extern u8 bob_dl_LightWall_64x64_ci4_ci4_pal_rgba16[];
extern u8 bob_dl_Diddy_Kong_Racing_48432BC3_0_2_all_rgba16[];
extern u8 bob_dl_DK_grass_64x64_ci4_ci4[];
extern u8 bob_dl_DK_grass_64x64_ci4_ci4_pal_rgba16[];
extern u8 bob_dl_grassy_stone_64x64_ci4_ci4[];
extern u8 bob_dl_grassy_stone_64x64_ci4_ci4_pal_rgba16[];
extern u8 bob_dl_OSC_O_J_ROAD01_M7_ci4[];
extern u8 bob_dl_OSC_O_J_ROAD01_M7_ci4_pal_rgba16[];
extern Vtx bob_dl_Cube_001_mesh_layer_5_vtx_cull[8];
extern Vtx bob_dl_Cube_001_mesh_layer_5_vtx_0[8];
extern Gfx bob_dl_Cube_001_mesh_layer_5_tri_0[];
extern Vtx bob_dl_Cube_001_mesh_layer_1_vtx_cull[8];
extern Vtx bob_dl_Cube_001_mesh_layer_1_vtx_0[4];
extern Gfx bob_dl_Cube_001_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Cube_mesh_layer_1_vtx_cull[8];
extern Vtx bob_dl_Cube_mesh_layer_1_vtx_0[18];
extern Gfx bob_dl_Cube_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Cube_mesh_layer_1_vtx_1[112];
extern Gfx bob_dl_Cube_mesh_layer_1_tri_1[];
extern Vtx bob_dl_Cube_mesh_layer_1_vtx_2[28];
extern Gfx bob_dl_Cube_mesh_layer_1_tri_2[];
extern Vtx bob_dl_Cube_mesh_layer_1_vtx_3[250];
extern Gfx bob_dl_Cube_mesh_layer_1_tri_3[];
extern Vtx bob_dl_Cube_mesh_layer_1_vtx_4[60];
extern Gfx bob_dl_Cube_mesh_layer_1_tri_4[];
extern Vtx bob_dl_Cube_mesh_layer_1_vtx_5[6];
extern Gfx bob_dl_Cube_mesh_layer_1_tri_5[];
extern Vtx bob_dl_Cube_mesh_layer_5_vtx_cull[8];
extern Vtx bob_dl_Cube_mesh_layer_5_vtx_0[8];
extern Gfx bob_dl_Cube_mesh_layer_5_tri_0[];
extern Vtx bob_dl_Cube_mesh_layer_5_vtx_1[122];
extern Gfx bob_dl_Cube_mesh_layer_5_tri_1[];
extern Vtx bob_dl_Cube_mesh_layer_5_vtx_2[8];
extern Gfx bob_dl_Cube_mesh_layer_5_tri_2[];
extern Vtx bob_dl_Area_3_visual_mesh_layer_1_vtx_cull[8];
extern Vtx bob_dl_Area_3_visual_mesh_layer_1_vtx_0[137];
extern Gfx bob_dl_Area_3_visual_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Plane_001_mesh_layer_1_vtx_cull[8];
extern Vtx bob_dl_Plane_001_mesh_layer_1_vtx_0[384];
extern Gfx bob_dl_Plane_001_mesh_layer_1_tri_0[];
extern Vtx bob_dl_ColiseumVisual_mesh_layer_1_vtx_cull[8];
extern Vtx bob_dl_ColiseumVisual_mesh_layer_1_vtx_0[359];
extern Gfx bob_dl_ColiseumVisual_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Area_6_ground_mesh_layer_1_vtx_cull[8];
extern Vtx bob_dl_Area_6_ground_mesh_layer_1_vtx_0[179];
extern Gfx bob_dl_Area_6_ground_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Area_6_ground_mesh_layer_1_vtx_1[48];
extern Gfx bob_dl_Area_6_ground_mesh_layer_1_tri_1[];
extern Vtx bob_dl_area_7_map_mesh_layer_1_vtx_cull[8];
extern Vtx bob_dl_area_7_map_mesh_layer_1_vtx_0[1315];
extern Gfx bob_dl_area_7_map_mesh_layer_1_tri_0[];
extern Vtx bob_dl_area_8_mesh_layer_1_vtx_cull[8];
extern Vtx bob_dl_area_8_mesh_layer_1_vtx_0[212];
extern Gfx bob_dl_area_8_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Plane_002_mesh_layer_1_vtx_cull[8];
extern Vtx bob_dl_Plane_002_mesh_layer_1_vtx_0[400];
extern Gfx bob_dl_Plane_002_mesh_layer_1_tri_0[];
extern Gfx mat_bob_dl_multitex_grass_fade_001_layer5[];
extern Gfx mat_revert_bob_dl_multitex_grass_fade_001_layer5[];
extern Gfx mat_bob_dl_multitex_grass_layer1[];
extern Gfx mat_revert_bob_dl_multitex_grass_layer1[];
extern Gfx mat_bob_dl_lightWallFade[];
extern Gfx mat_revert_bob_dl_lightWallFade[];
extern Gfx mat_bob_dl_wallNofade[];
extern Gfx mat_bob_dl_f3dlite_material[];
extern Gfx mat_revert_bob_dl_f3dlite_material[];
extern Gfx mat_bob_dl_wallFade[];
extern Gfx mat_bob_dl_stone_wall_layer1[];
extern Gfx mat_revert_bob_dl_stone_wall_layer1[];
extern Gfx mat_bob_dl_floor[];
extern Gfx mat_revert_bob_dl_floor[];
extern Gfx mat_bob_dl_lightWallNoFade[];
extern Gfx mat_revert_bob_dl_lightWallNoFade[];
extern Gfx mat_bob_dl_cozies_noise_thing_green_layer1[];
extern Gfx mat_revert_bob_dl_cozies_noise_thing_green_layer1[];
extern Gfx mat_bob_dl_cozies_noise_thing_layer1[];
extern Gfx mat_revert_bob_dl_cozies_noise_thing_layer1[];
extern Gfx mat_bob_dl_cozies_noise_thing_no_AA_layer1[];
extern Gfx mat_revert_bob_dl_cozies_noise_thing_no_AA_layer1[];
extern Gfx mat_bob_dl_cozies_noise_thing_yellow_layer1[];
extern Gfx mat_revert_bob_dl_cozies_noise_thing_yellow_layer1[];
extern Gfx bob_dl_Cube_001_mesh_layer_5[];
extern Gfx bob_dl_Cube_001_mesh_layer_1[];
extern Gfx bob_dl_Cube_mesh_layer_1[];
extern Gfx bob_dl_Cube_mesh_layer_5[];
extern Gfx bob_dl_Area_3_visual_mesh_layer_1[];
extern Gfx bob_dl_Plane_001_mesh_layer_1[];
extern Gfx bob_dl_ColiseumVisual_mesh_layer_1[];
extern Gfx bob_dl_Area_6_ground_mesh_layer_1[];
extern Gfx bob_dl_area_7_map_mesh_layer_1[];
extern Gfx bob_dl_area_8_mesh_layer_1[];
extern Gfx bob_dl_Plane_002_mesh_layer_1[];
extern Gfx bob_dl_material_revert_render_settings[];
