extern const GeoLayout bob_area_1_geo[];
extern const GeoLayout bob_area_1[];
extern const Collision bob_area_1_collision[];
extern const MacroObject bob_area_1_macro_objs[];
extern const GeoLayout bob_area_2_geo[];
extern const GeoLayout bob_area_2[];
extern const Collision bob_area_2_collision[];
extern const MacroObject bob_area_2_macro_objs[];
extern u8 bob_dl_Z2_00KEIKOKUTex_02C050_rgba16_rgba16[];
extern u8 bob_dl_Grass_rgba16[];
extern u8 bob_dl_Diddy_Kong_Racing_48432BC3_0_2_all_rgba16[];
extern u8 bob_dl_DK_grass_64x64_ci4_ci4[];
extern u8 bob_dl_DK_grass_64x64_ci4_ci4_pal_rgba16[];
extern u8 bob_dl_grassy_stone_64x64_ci4_ci4[];
extern u8 bob_dl_grassy_stone_64x64_ci4_ci4_pal_rgba16[];
extern u8 bob_dl_OSC_O_J_ROAD01_M7_ci4[];
extern u8 bob_dl_OSC_O_J_ROAD01_M7_ci4_pal_rgba16[];
extern Vtx bob_dl_Cube_001_mesh_layer_1_vtx_cull[8];
extern Vtx bob_dl_Cube_001_mesh_layer_1_vtx_0[4];
extern Gfx bob_dl_Cube_001_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Cube_mesh_layer_1_vtx_cull[8];
extern Vtx bob_dl_Cube_mesh_layer_1_vtx_0[34];
extern Gfx bob_dl_Cube_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Cube_mesh_layer_1_vtx_1[116];
extern Gfx bob_dl_Cube_mesh_layer_1_tri_1[];
extern Vtx bob_dl_Cube_mesh_layer_1_vtx_2[28];
extern Gfx bob_dl_Cube_mesh_layer_1_tri_2[];
extern Vtx bob_dl_Cube_mesh_layer_1_vtx_3[198];
extern Gfx bob_dl_Cube_mesh_layer_1_tri_3[];
extern Vtx bob_dl_Cube_mesh_layer_1_vtx_4[60];
extern Gfx bob_dl_Cube_mesh_layer_1_tri_4[];
extern Vtx bob_dl_Cube_mesh_layer_5_vtx_cull[8];
extern Vtx bob_dl_Cube_mesh_layer_5_vtx_0[120];
extern Gfx bob_dl_Cube_mesh_layer_5_tri_0[];
extern Vtx bob_dl_Cube_mesh_layer_5_vtx_1[76];
extern Gfx bob_dl_Cube_mesh_layer_5_tri_1[];
extern Gfx mat_bob_dl_black[];
extern Gfx mat_bob_dl_sm64_material_001_layer1[];
extern Gfx mat_revert_bob_dl_sm64_material_001_layer1[];
extern Gfx mat_bob_dl_wallNofade[];
extern Gfx mat_bob_dl_f3dlite_material[];
extern Gfx mat_revert_bob_dl_f3dlite_material[];
extern Gfx mat_bob_dl_wallFade[];
extern Gfx mat_bob_dl_stone_wall[];
extern Gfx mat_revert_bob_dl_stone_wall[];
extern Gfx mat_bob_dl_floor[];
extern Gfx mat_revert_bob_dl_floor[];
extern Gfx mat_bob_dl_stone_wall_fade[];
extern Gfx mat_revert_bob_dl_stone_wall_fade[];
extern Gfx bob_dl_Cube_001_mesh_layer_1[];
extern Gfx bob_dl_Cube_mesh_layer_1[];
extern Gfx bob_dl_Cube_mesh_layer_5[];
extern Gfx bob_dl_material_revert_render_settings[];
