extern const GeoLayout bob_area_1_geo[];
extern const GeoLayout bob_area_1[];
extern const Collision bob_area_1_collision[];
extern const MacroObject bob_area_1_macro_objs[];
extern const GeoLayout bob_area_2_geo[];
extern const GeoLayout bob_area_2[];
extern const Collision bob_area_2_collision[];
extern const MacroObject bob_area_2_macro_objs[];
extern const GeoLayout bob_area_3_geo[];
extern const GeoLayout bob_area_3[];
extern const Collision bob_area_3_collision[];
extern const MacroObject bob_area_3_macro_objs[];
extern const GeoLayout bob_area_4_geo[];
extern const GeoLayout bob_area_4[];
extern const Collision bob_area_4_collision[];
extern const MacroObject bob_area_4_macro_objs[];
extern const GeoLayout bob_area_5_geo[];
extern const GeoLayout bob_area_5[];
extern const Collision bob_area_5_collision[];
extern const MacroObject bob_area_5_macro_objs[];
extern const GeoLayout bob_area_6_geo[];
extern const GeoLayout bob_area_6[];
extern const Collision bob_area_6_collision[];
extern const MacroObject bob_area_6_macro_objs[];
extern const Trajectory bob_area_6_spline_NurbsCurve[];
extern u8 bob_dl_Z2_00KEIKOKUTex_02C050_rgba16_rgba16[];
extern u8 bob_dl_Grass_rgba16[];
extern u8 bob_dl_LightWall_64x64_ci4_ci4[];
extern u8 bob_dl_LightWall_64x64_ci4_ci4_pal_rgba16[];
extern u8 bob_dl_Diddy_Kong_Racing_48432BC3_0_2_all_rgba16[];
extern u8 bob_dl_DK_grass_64x64_ci4_ci4[];
extern u8 bob_dl_DK_grass_64x64_ci4_ci4_pal_rgba16[];
extern u8 bob_dl_grassy_stone_64x64_ci4_ci4[];
extern u8 bob_dl_grassy_stone_64x64_ci4_ci4_pal_rgba16[];
extern u8 bob_dl_OSC_O_J_ROAD01_M7_ci4[];
extern u8 bob_dl_OSC_O_J_ROAD01_M7_ci4_pal_rgba16[];
extern Vtx bob_dl_Cube_001_mesh_layer_5_vtx_cull[8];
extern Vtx bob_dl_Cube_001_mesh_layer_5_vtx_0[8];
extern Gfx bob_dl_Cube_001_mesh_layer_5_tri_0[];
extern Vtx bob_dl_Cube_001_mesh_layer_1_vtx_cull[8];
extern Vtx bob_dl_Cube_001_mesh_layer_1_vtx_0[4];
extern Gfx bob_dl_Cube_001_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Cube_mesh_layer_1_vtx_cull[8];
extern Vtx bob_dl_Cube_mesh_layer_1_vtx_0[18];
extern Gfx bob_dl_Cube_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Cube_mesh_layer_1_vtx_1[112];
extern Gfx bob_dl_Cube_mesh_layer_1_tri_1[];
extern Vtx bob_dl_Cube_mesh_layer_1_vtx_2[28];
extern Gfx bob_dl_Cube_mesh_layer_1_tri_2[];
extern Vtx bob_dl_Cube_mesh_layer_1_vtx_3[198];
extern Gfx bob_dl_Cube_mesh_layer_1_tri_3[];
extern Vtx bob_dl_Cube_mesh_layer_1_vtx_4[60];
extern Gfx bob_dl_Cube_mesh_layer_1_tri_4[];
extern Vtx bob_dl_Cube_mesh_layer_1_vtx_5[4];
extern Gfx bob_dl_Cube_mesh_layer_1_tri_5[];
extern Vtx bob_dl_Cube_mesh_layer_5_vtx_cull[8];
extern Vtx bob_dl_Cube_mesh_layer_5_vtx_0[8];
extern Gfx bob_dl_Cube_mesh_layer_5_tri_0[];
extern Vtx bob_dl_Cube_mesh_layer_5_vtx_1[122];
extern Gfx bob_dl_Cube_mesh_layer_5_tri_1[];
extern Vtx bob_dl_Cube_mesh_layer_5_vtx_2[76];
extern Gfx bob_dl_Cube_mesh_layer_5_tri_2[];
extern Vtx bob_dl_Cube_mesh_layer_5_vtx_3[8];
extern Gfx bob_dl_Cube_mesh_layer_5_tri_3[];
extern Vtx bob_dl_Plane_mesh_layer_1_vtx_cull[8];
extern Vtx bob_dl_Plane_mesh_layer_1_vtx_0[20];
extern Gfx bob_dl_Plane_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Plane_mesh_layer_1_vtx_1[8];
extern Gfx bob_dl_Plane_mesh_layer_1_tri_1[];
extern Vtx bob_dl_Plane_mesh_layer_5_vtx_cull[8];
extern Vtx bob_dl_Plane_mesh_layer_5_vtx_0[20];
extern Gfx bob_dl_Plane_mesh_layer_5_tri_0[];
extern Vtx bob_dl_Plane_001_mesh_layer_1_vtx_cull[8];
extern Vtx bob_dl_Plane_001_mesh_layer_1_vtx_0[384];
extern Gfx bob_dl_Plane_001_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Coliseum_mesh_layer_1_vtx_cull[8];
extern Vtx bob_dl_Coliseum_mesh_layer_1_vtx_0[84];
extern Gfx bob_dl_Coliseum_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Cube_002_mesh_layer_1_vtx_cull[8];
extern Vtx bob_dl_Cube_002_mesh_layer_1_vtx_0[24];
extern Gfx bob_dl_Cube_002_mesh_layer_1_tri_0[];
extern Gfx mat_bob_dl_multitex_grass_fade_001_layer5[];
extern Gfx mat_revert_bob_dl_multitex_grass_fade_001_layer5[];
extern Gfx mat_bob_dl_multitex_grass_layer1[];
extern Gfx mat_revert_bob_dl_multitex_grass_layer1[];
extern Gfx mat_bob_dl_lightWallFade[];
extern Gfx mat_revert_bob_dl_lightWallFade[];
extern Gfx mat_bob_dl_wallNofade[];
extern Gfx mat_bob_dl_f3dlite_material[];
extern Gfx mat_revert_bob_dl_f3dlite_material[];
extern Gfx mat_bob_dl_wallFade[];
extern Gfx mat_bob_dl_stone_wall[];
extern Gfx mat_revert_bob_dl_stone_wall[];
extern Gfx mat_bob_dl_floor[];
extern Gfx mat_revert_bob_dl_floor[];
extern Gfx mat_bob_dl_stone_wall_fade[];
extern Gfx mat_revert_bob_dl_stone_wall_fade[];
extern Gfx mat_bob_dl_lightWallNoFade[];
extern Gfx mat_revert_bob_dl_lightWallNoFade[];
extern Gfx mat_bob_dl_cozies_noise_thing_layer1[];
extern Gfx mat_revert_bob_dl_cozies_noise_thing_layer1[];
extern Gfx bob_dl_Cube_001_mesh_layer_5[];
extern Gfx bob_dl_Cube_001_mesh_layer_1[];
extern Gfx bob_dl_Cube_mesh_layer_1[];
extern Gfx bob_dl_Cube_mesh_layer_5[];
extern Gfx bob_dl_Plane_mesh_layer_1[];
extern Gfx bob_dl_Plane_mesh_layer_5[];
extern Gfx bob_dl_Plane_001_mesh_layer_1[];
extern Gfx bob_dl_Coliseum_mesh_layer_1[];
extern Gfx bob_dl_Cube_002_mesh_layer_1[];
extern Gfx bob_dl_material_revert_render_settings[];
