extern const GeoLayout moving_platform_geo_geo[];
extern Vtx moving_platform_geo_moving_platform_geo_mesh_layer_1_vtx_cull[8];
extern Vtx moving_platform_geo_moving_platform_geo_mesh_layer_1_vtx_0[24];
extern Gfx moving_platform_geo_moving_platform_geo_mesh_layer_1_tri_0[];
extern Gfx mat_moving_platform_geo_cozies_noise_thing_layer1[];
extern Gfx mat_revert_moving_platform_geo_cozies_noise_thing_layer1[];
extern Gfx moving_platform_geo_moving_platform_geo_mesh_layer_1[];
extern Gfx moving_platform_geo_material_revert_render_settings[];
