extern const GeoLayout wf_area_1_geo[];
extern const GeoLayout wf_area_1[];
extern const Collision wf_area_1_collision[];
extern const MacroObject wf_area_1_macro_objs[];
extern const Trajectory wf_area_1_spline_ASplineChallenge0A_004[];
extern const Trajectory wf_area_1_spline_ASplineChallenge11[];
extern const Trajectory wf_area_1_spline_ASplineChallenge11_001[];
extern Vtx wf_dl_Plane_003_mesh_layer_1_vtx_cull[8];
extern Vtx wf_dl_Plane_003_mesh_layer_1_vtx_0[4];
extern Gfx wf_dl_Plane_003_mesh_layer_1_tri_0[];
extern Gfx mat_wf_dl_cozies_noise_thing_layer1[];
extern Gfx mat_revert_wf_dl_cozies_noise_thing_layer1[];
extern Gfx wf_dl_Plane_003_mesh_layer_1[];
extern Gfx wf_dl_material_revert_render_settings[];
