extern const GeoLayout wf_area_1_geo[];
extern const GeoLayout wf_area_1[];
extern const Collision wf_area_1_collision[];
extern const MacroObject wf_area_1_macro_objs[];
extern const Trajectory wf_area_1_spline_ASplineChallenge11[];
extern const Trajectory wf_area_1_spline_ASplineChallenge11_001[];
extern const Trajectory wf_area_1_spline_ASplineChallenge11_002[];
extern const Trajectory wf_area_1_spline_ASplineChallenge11_003[];
extern const GeoLayout wf_area_2_geo[];
extern const GeoLayout wf_area_2[];
extern const Collision wf_area_2_collision[];
extern const MacroObject wf_area_2_macro_objs[];
extern u8 wf_dl_darklava_32x32_rgba16_rgba16[];
extern u8 wf_dl_lightlava_32x32_rgba16_rgba16[];
extern Vtx wf_dl_Plane_003_mesh_layer_1_vtx_cull[8];
extern Vtx wf_dl_Plane_003_mesh_layer_1_vtx_0[24];
extern Gfx wf_dl_Plane_003_mesh_layer_1_tri_0[];
extern Vtx wf_dl_Area_2_WF_mesh_layer_1_vtx_cull[8];
extern Vtx wf_dl_Area_2_WF_mesh_layer_1_vtx_0[333];
extern Gfx wf_dl_Area_2_WF_mesh_layer_1_tri_0[];
extern Vtx wf_dl_Area_2_WF_mesh_layer_1_vtx_1[8];
extern Gfx wf_dl_Area_2_WF_mesh_layer_1_tri_1[];
extern Gfx mat_wf_dl_cozies_noise_thing_layer1[];
extern Gfx mat_revert_wf_dl_cozies_noise_thing_layer1[];
extern Gfx mat_wf_dl_f3dlite_material_005_layer1[];
extern Gfx mat_revert_wf_dl_f3dlite_material_005_layer1[];
extern Gfx wf_dl_Plane_003_mesh_layer_1[];
extern Gfx wf_dl_Area_2_WF_mesh_layer_1[];
extern Gfx wf_dl_material_revert_render_settings[];
