extern const GeoLayout penguin_000_switch_opt1[];
extern const GeoLayout penguin_000_switch_opt2[];
extern const GeoLayout penguin_000_switch_opt3[];
extern const GeoLayout penguin_000_switch_opt4[];
extern const GeoLayout penguin_000_switch_opt5[];
extern const GeoLayout penguin_geo[];
extern u8 penguin_penguin_eye_open_rgba16_ci8[];
extern u8 penguin_penguin_eye_open_rgba16_ci8_pal_rgba16[];
extern u8 penguin_penguin_beak_rgba16_ci8[];
extern u8 penguin_penguin_beak_rgba16_ci8_pal_rgba16[];
extern u8 penguin_penguin_eye_half_closed_rgba16_ci8[];
extern u8 penguin_penguin_eye_half_closed_rgba16_ci8_pal_rgba16[];
extern u8 penguin_penguin_eye_angry_rgba16_ci8[];
extern u8 penguin_penguin_eye_angry_rgba16_ci8_pal_rgba16[];
extern u8 penguin_penguin_eye_closed_rgba16_ci8[];
extern u8 penguin_penguin_eye_closed_rgba16_ci8_pal_rgba16[];
extern u8 penguin_penguin_eye_angry_unused_rgba16_ci8[];
extern u8 penguin_penguin_eye_angry_unused_rgba16_ci8_pal_rgba16[];
extern Vtx penguin_000_offset_mesh_layer_1_vtx_0[39];
extern Gfx penguin_000_offset_mesh_layer_1_tri_0[];
extern Vtx penguin_000_offset_mesh_layer_1_vtx_1[12];
extern Gfx penguin_000_offset_mesh_layer_1_tri_1[];
extern Vtx penguin_000_offset_002_mesh_layer_1_vtx_0[5];
extern Gfx penguin_000_offset_002_mesh_layer_1_tri_0[];
extern Vtx penguin_000_offset_003_mesh_layer_1_vtx_0[5];
extern Gfx penguin_000_offset_003_mesh_layer_1_tri_0[];
extern Vtx penguin_000_offset_004_mesh_layer_1_vtx_0[9];
extern Gfx penguin_000_offset_004_mesh_layer_1_tri_0[];
extern Vtx penguin_000_offset_005_mesh_layer_1_vtx_0[9];
extern Gfx penguin_000_offset_005_mesh_layer_1_tri_0[];
extern Vtx penguin_000_offset_006_mesh_layer_1_vtx_0[45];
extern Gfx penguin_000_offset_006_mesh_layer_1_tri_0[];
extern Vtx penguin_000_offset_006_mesh_layer_1_vtx_1[8];
extern Gfx penguin_000_offset_006_mesh_layer_1_tri_1[];
extern Vtx penguin_000_offset_006_mesh_layer_1_vtx_2[7];
extern Gfx penguin_000_offset_006_mesh_layer_1_tri_2[];
extern Gfx mat_penguin_blue_penguin_layer1[];
extern Gfx mat_revert_penguin_blue_penguin_layer1[];
extern Gfx mat_penguin_f3dlite_material_004_layer1[];
extern Gfx mat_revert_penguin_f3dlite_material_004_layer1[];
extern Gfx mat_penguin_feet_layer1[];
extern Gfx mat_revert_penguin_feet_layer1[];
extern Gfx mat_penguin_eyes_open_layer1[];
extern Gfx mat_revert_penguin_eyes_open_layer1[];
extern Gfx mat_penguin_peak_layer1[];
extern Gfx mat_revert_penguin_peak_layer1[];
extern Gfx mat_penguin_eyes_half_closed_layer1[];
extern Gfx mat_revert_penguin_eyes_half_closed_layer1[];
extern Gfx mat_penguin_eyes_angry_layer1[];
extern Gfx mat_revert_penguin_eyes_angry_layer1[];
extern Gfx mat_penguin_eyes_closed_layer1[];
extern Gfx mat_revert_penguin_eyes_closed_layer1[];
extern Gfx mat_penguin_eyes_sad_layer1[];
extern Gfx mat_revert_penguin_eyes_sad_layer1[];
extern Gfx penguin_000_offset_mesh_layer_1[];
extern Gfx penguin_000_offset_002_mesh_layer_1[];
extern Gfx penguin_000_offset_003_mesh_layer_1[];
extern Gfx penguin_000_offset_004_mesh_layer_1[];
extern Gfx penguin_000_offset_005_mesh_layer_1[];
extern Gfx penguin_000_offset_006_mesh_layer_1[];
extern Gfx penguin_000_offset_006_mesh_layer_1_mat_override_eyes_open_0[];
extern Gfx penguin_000_offset_006_mesh_layer_1_mat_override_eyes_half_closed_1[];
extern Gfx penguin_000_offset_006_mesh_layer_1_mat_override_eyes_angry_2[];
extern Gfx penguin_000_offset_006_mesh_layer_1_mat_override_eyes_closed_3[];
extern Gfx penguin_000_offset_006_mesh_layer_1_mat_override_eyes_sad_4[];
extern Gfx penguin_material_revert_render_settings[];
