extern const GeoLayout platform3_rr_mayro_geo[];
extern Vtx platform3_rr_mayro_platform3_rr_mayro_mesh_layer_1_vtx_cull[8];
extern Vtx platform3_rr_mayro_platform3_rr_mayro_mesh_layer_1_vtx_0[32];
extern Gfx platform3_rr_mayro_platform3_rr_mayro_mesh_layer_1_tri_0[];
extern Gfx mat_platform3_rr_mayro_sm64_material_001_layer1[];
extern Gfx mat_revert_platform3_rr_mayro_sm64_material_001_layer1[];
extern Gfx platform3_rr_mayro_platform3_rr_mayro_mesh_layer_1[];
extern Gfx platform3_rr_mayro_material_revert_render_settings[];
